<?php
// CLI helper: converts ADMIN_PASSWORD_PLAIN in config.php to ADMIN_PASSWORD_HASH and removes the plaintext line.
// Usage: php convert_admin_password.php

if (php_sapi_name() !== 'cli') {
    echo "This script must be run from the command line.\n";
    exit(1);
}

$configFile = __DIR__ . '/../config.php';
if (!file_exists($configFile)) {
    echo "config.php not found at: $configFile\n";
    exit(1);
}

// Load config to read current plaintext value if present
require $configFile;

if (!defined('ADMIN_PASSWORD_PLAIN') || ADMIN_PASSWORD_PLAIN === '') {
    echo "No ADMIN_PASSWORD_PLAIN defined in config.php. Nothing to do.\n";
    exit(0);
}

$plain = ADMIN_PASSWORD_PLAIN;
$hash = password_hash($plain, PASSWORD_DEFAULT);
if ($hash === false) {
    echo "Failed to generate password hash.\n";
    exit(1);
}

// Read file contents and replace the define line
$cfg = file_get_contents($configFile);
if ($cfg === false) {
    echo "Failed to read config.php\n";
    exit(1);
}

// Pattern to remove ADMIN_PASSWORD_PLAIN define and optionally insert ADMIN_PASSWORD_HASH
$pattern = "/define\(\s*'ADMIN_PASSWORD_PLAIN'\s*,\s*'([\\s\\S]*?)'\s*\)\s*;?/";
if (preg_match($pattern, $cfg)) {
    // Remove plaintext define
    $cfg = preg_replace($pattern, "", $cfg, 1);
    // Insert hashed define near the top (after PHP opening and comments)
    $insert = "\n// Admin password hash (generated by convert_admin_password.php)\ndefine('ADMIN_PASSWORD_HASH', " . var_export($hash, true) . ");\n";
    // Place the insert after the initial PHP tag and header comments if possible
    if (preg_match('/<\?php\s*/', $cfg, $m, PREG_OFFSET_CAPTURE)) {
        $pos = strpos($cfg, "\n", $m[0][1]);
        if ($pos !== false) {
            $cfg = substr_replace($cfg, $insert, $pos + 1, 0);
        } else {
            $cfg = $insert . $cfg;
        }
    } else {
        $cfg = $insert . $cfg;
    }

    // Write back atomically
    $tmp = $configFile . '.tmp';
    if (file_put_contents($tmp, $cfg) === false) {
        echo "Failed to write temporary config file.\n";
        exit(1);
    }
    if (!rename($tmp, $configFile)) {
        echo "Failed to install new config file.\n";
        exit(1);
    }

    echo "ADMIN_PASSWORD_PLAIN converted to ADMIN_PASSWORD_HASH and plaintext removed from config.php.\n";
    echo "Please verify and then delete this script for security.\n";
    exit(0);
} else {
    echo "Could not find ADMIN_PASSWORD_PLAIN define in config.php; nothing changed.\n";
    exit(1);
}
